# Generated by Django 3.1.3 on 2022-05-26 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='lesson',
            new_name='question',
        ),
    ]
